import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Activity, CircleCheck, CircleX, Clock3, ShieldCheck } from "lucide-react";

export default function Performance() {
  const stats = trpc.predictions.statistics.useQuery();
  const history = trpc.results.history.useQuery();
  const breakdown = trpc.results.breakdown.useQuery();
  const totalSettled = (stats.data?.won ?? 0) + (stats.data?.lost ?? 0);
  const rate = totalSettled ? Math.round(((stats.data?.won ?? 0) / totalSettled) * 100) : null;

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-5 pb-5 sm:space-y-7 sm:pb-12">
    <header className="rounded-3xl border border-border/70 bg-card/75 p-5 sm:rounded-[2rem] sm:p-7"><div className="flex items-center gap-2"><span className="relative flex h-7 w-7 items-center justify-center rounded-lg border border-primary/35 bg-primary/10 text-primary shadow-[0_0_24px_rgba(70,202,142,0.13)]"><ShieldCheck className="h-3.5 w-3.5" /><span className="absolute -bottom-0.5 left-1/2 h-0.5 w-3 -translate-x-1/2 rounded-full bg-primary" /></span><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-primary sm:text-xs">Istoric verificat</p></div><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:mt-3 sm:text-3xl">Performanță din rezultate confirmate.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground sm:mt-3">Indicatorii se calculează doar după decontare. Pe măsură ce API-ul confirmă rezultate, istoricul devine mai util pentru piețe și strategii.</p></header>
    <section className="grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4"><Stat icon={Activity} label="Total selecții" value={stats.data?.total ?? "—"} /><Stat icon={CircleCheck} label="Câștigătoare" value={stats.data?.won ?? "—"} /><Stat icon={CircleX} label="Pierdute" value={stats.data?.lost ?? "—"} /><Stat icon={Clock3} label="Rată finalizată" value={rate === null ? "—" : `${rate}%`} /></section>
    <section className="rounded-3xl border border-border/70 bg-card/65 p-5 sm:p-6"><h2 className="text-lg font-semibold text-foreground">Performanță pe piață</h2>{breakdown.data?.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{breakdown.data.map(item => <div key={`${item.sport}-${item.market}`} className="rounded-2xl border border-border/60 bg-background/25 p-4"><div className="flex items-center justify-between gap-3"><p className="truncate font-medium text-foreground">{item.market}</p><span className="shrink-0 text-xs font-semibold text-primary">{item.sport}</span></div><p className="mt-2 text-sm text-muted-foreground">{item.total} rezultate · {item.won} câștigate · {item.lost} pierdute</p><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Rată" value={item.winRate === null ? "—" : `${item.winRate}%`} /><Metric label="Cotă medie" value={item.avgOdds === null ? "—" : Number(item.avgOdds).toFixed(2)} /></div></div>)}</div> : <Empty>Nu există încă suficient istoric finalizat pentru o împărțire pe piețe.</Empty>}</section>
    <section className="rounded-3xl border border-border/70 bg-card/65 p-5 sm:p-6"><h2 className="text-lg font-semibold text-foreground">Rezultate recente</h2>{history.data?.length ? <><div className="mt-4 space-y-2.5 md:hidden">{history.data.map(item => <ResultCard key={item.id} item={item} />)}</div><div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-3">Meci</th><th className="pb-3">Piață</th><th className="pb-3">Scor</th><th className="pb-3">Cotă</th><th className="pb-3">Statut</th></tr></thead><tbody>{history.data.map(item => <tr key={item.id} className="border-b border-border/50"><td className="py-3 text-foreground">{item.homeTeam} — {item.awayTeam}</td><td className="py-3 text-muted-foreground">{item.label}</td><td className="py-3 text-muted-foreground">{item.homeScore ?? "—"}:{item.awayScore ?? "—"}</td><td className="py-3 text-muted-foreground">{item.currentOdds ? Number(item.currentOdds).toFixed(2) : "—"}</td><td className={`py-3 font-medium ${statusTone(item.settlementStatus)}`}>{item.settlementStatus}</td></tr>)}</tbody></table></div></> : <Empty>Rezultatele vor apărea automat după confirmarea evenimentelor de către API.</Empty>}</section>
  </div></DashboardLayout>;
}

function statusTone(status: string) { return status === "won" ? "text-emerald-300" : status === "lost" ? "text-rose-300" : "text-muted-foreground"; }
function Stat({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string | number }) { return <div className="rounded-2xl border border-border/65 bg-card/70 p-4 sm:p-5"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground sm:mt-5">{label}</p><p className="mt-1 text-2xl font-semibold text-foreground">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-background/35 p-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold text-foreground">{value}</p></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="mt-4 rounded-2xl border border-dashed border-border/70 p-4 text-sm leading-6 text-muted-foreground">{children}</p>; }
function ResultCard({ item }: { item: { homeTeam: string; awayTeam: string; label: string; homeScore: number | null; awayScore: number | null; currentOdds: string | null; settlementStatus: string } }) { return <article className="rounded-2xl border border-border/60 bg-background/25 p-3.5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-foreground">{item.homeTeam} <span className="text-muted-foreground">—</span> {item.awayTeam}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.label}</p></div><p className={`shrink-0 text-xs font-semibold capitalize ${statusTone(item.settlementStatus)}`}>{item.settlementStatus}</p></div><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Scor" value={`${item.homeScore ?? "—"}:${item.awayScore ?? "—"}`} /><Metric label="Cotă" value={item.currentOdds ? Number(item.currentOdds).toFixed(2) : "—"} /></div></article>; }
