import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BellRing, ShieldCheck, UserRound } from "lucide-react";

export default function Profile() {
  const { user } = useAuth();
  const preferences = trpc.profile.notificationPreferences.useQuery();
  const notifications = trpc.notifications.list.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-5xl space-y-5 pb-5 sm:space-y-7 sm:pb-12">
    <header className="rounded-3xl border border-border/70 bg-card/75 p-5 sm:rounded-[2rem] sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-primary sm:text-xs">Centrul contului</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:mt-3 sm:text-3xl">Profil și preferințe.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground sm:mt-3">Contul este protejat prin Manus OAuth. Alertele urmăresc predicțiile și rezultatele confirmate, fără promisiuni privind rezultate.</p></header>
    <section className="grid gap-4 md:grid-cols-2 md:gap-6"><div className="rounded-3xl border border-border/70 bg-card/70 p-5 sm:p-6"><UserRound className="h-6 w-6 text-primary" /><p className="mt-4 text-xs text-muted-foreground sm:mt-5">Utilizator autentificat</p><p className="mt-1 truncate text-xl font-semibold text-foreground">{user?.name ?? "—"}</p><p className="mt-1 truncate text-sm text-muted-foreground">{user?.email ?? "Fără e-mail disponibil"}</p></div><div className="rounded-3xl border border-border/70 bg-card/70 p-5 sm:p-6"><BellRing className="h-6 w-6 text-primary" /><p className="mt-4 text-xs text-muted-foreground sm:mt-5">Notificări configurate</p><div className="mt-3 space-y-2.5">{[{ label: "Predicții zilnice", enabled: preferences.data?.dailyPredictions }, { label: "Rezultate confirmate", enabled: preferences.data?.resultsConfirmed }, { label: "Mișcare de cote", enabled: preferences.data?.oddsMovement }].map(item => <div key={item.label} className="flex items-center justify-between rounded-xl border border-border/55 bg-background/25 px-3 py-2.5 text-sm"><span className="text-foreground">{item.label}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${item.enabled ? "bg-primary/15 text-primary" : "bg-muted text-muted-foreground"}`}>{item.enabled ? "activă" : "inactivă"}</span></div>)}</div></div></section>
    <section className="rounded-3xl border border-border/70 bg-card/60 p-5 sm:p-6"><h2 className="text-lg font-semibold text-foreground">Alerte recente</h2>{notifications.data?.length ? <div className="mt-4 space-y-2.5">{notifications.data.map(item => <article key={item.id} className="rounded-2xl border border-border/55 bg-background/25 p-3.5 sm:p-4"><p className="font-medium text-foreground">{item.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.content}</p></article>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-border/70 p-4 text-sm leading-6 text-muted-foreground">Nu ai încă notificări. Acestea apar după prima actualizare programată care publică predicții sau confirmă rezultate.</p>}</section>
    <section className="flex gap-3 rounded-3xl border border-border/70 bg-card/60 p-5 text-sm leading-6 text-muted-foreground sm:p-6"><ShieldCheck className="h-5 w-5 shrink-0 text-primary" />Datele de conectare la API sunt stocate exclusiv pe server. Pentru transparență, aplicația afișează disponibilitatea datelor, sursa cotei și rezultatele confirmate, nu certitudini.</section>
  </div></DashboardLayout>;
}
