import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BellRing, ShieldCheck, UserRound } from "lucide-react";

export default function Profile() {
  const { user } = useAuth();
  const preferences = trpc.profile.notificationPreferences.useQuery();
  const notifications = trpc.notifications.list.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-5xl space-y-7 pb-12"><header className="rounded-[2rem] border border-border/70 bg-card/75 p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Account center</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-foreground">Profil și preferințe.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Contul este autentificat prin Manus OAuth. Preferințele de notificare sunt pregătite pentru alertele de predicții și rezultate confirmate.</p></header><section className="grid gap-6 md:grid-cols-2"><div className="rounded-3xl border border-border/70 bg-card/70 p-6"><UserRound className="h-6 w-6 text-primary" /><p className="mt-5 text-xs text-muted-foreground">Utilizator autentificat</p><p className="mt-1 text-xl font-semibold text-foreground">{user?.name ?? "—"}</p><p className="mt-1 text-sm text-muted-foreground">{user?.email ?? "Fără e-mail disponibil"}</p></div><div className="rounded-3xl border border-border/70 bg-card/70 p-6"><BellRing className="h-6 w-6 text-primary" /><p className="mt-5 text-xs text-muted-foreground">Notificări configurate</p><div className="mt-3 space-y-2 text-sm text-foreground"><p>Predicții zilnice: <strong>{preferences.data?.dailyPredictions ? "active" : "inactive"}</strong></p><p>Rezultate confirmate: <strong>{preferences.data?.resultsConfirmed ? "active" : "inactive"}</strong></p><p>Mișcare de cote: <strong>{preferences.data?.oddsMovement ? "activă" : "inactivă"}</strong></p></div></div></section><section className="rounded-3xl border border-border/70 bg-card/60 p-6"><h2 className="text-lg font-semibold text-foreground">Alerte recente</h2>{notifications.data?.length ? <div className="mt-4 space-y-3">{notifications.data.map(item => <div key={item.id} className="rounded-2xl border border-border/55 bg-background/25 p-4"><p className="font-medium text-foreground">{item.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.content}</p></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">Nu ai încă notificări. Acestea vor apărea după prima actualizare programată care publică predicții sau confirmă rezultate.</p>}</section><section className="flex gap-3 rounded-3xl border border-border/70 bg-card/60 p-6 text-sm leading-6 text-muted-foreground"><ShieldCheck className="h-5 w-5 shrink-0 text-primary" /> Datele de conectare la API sunt stocate exclusiv pe server. Pentru transparență, aplicația afișează disponibilitatea datelor, sursa cotei și rezultatele confirmate, nu certitudini.</section></div></DashboardLayout>;
}
