import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Calculator, ChevronRight, Layers3, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function Strategies() {
  const [target, setTarget] = useState(1.4);
  const [horizonDays, setHorizonDays] = useState(1);
  const [baseStake, setBaseStake] = useState(10);
  const [maxSteps, setMaxSteps] = useState(5);
  const [reinvestRate, setReinvestRate] = useState(50);
  const [profitLockRate, setProfitLockRate] = useState(30);
  const ticketInput = useMemo(() => ({ targetOddsMin: Math.max(1.05, target - 0.08), targetOddsMax: target + 0.08, maxSelections: 4, horizonDays }), [horizonDays, target]);
  const suggestion = trpc.tickets.suggest.useQuery(ticketInput);
  const utils = trpc.useUtils();
  const plans = trpc.pyramids.list.useQuery();
  const createPlan = trpc.pyramids.create.useMutation({ onSuccess: () => { toast.success("Piramida a fost creată."); utils.pyramids.list.invalidate(); }, onError: error => toast.error(error.message) });
  const plan = suggestion.data;
  const pyramidProjection = useMemo(() => {
    let bankroll = baseStake;
    return Array.from({ length: maxSteps }, (_, index) => {
      const retained = index === 0 ? 0 : Math.max(0, bankroll - baseStake) * (profitLockRate / 100);
      const stake = index === 0 ? baseStake : Math.min((bankroll - retained) * (reinvestRate / 100), bankroll * 0.6);
      const potentialReturn = stake * target;
      const profit = potentialReturn - stake;
      const row = { step: index + 1, stake, potentialReturn, profit, retained };
      bankroll = bankroll - stake + potentialReturn;
      return row;
    });
  }, [baseStake, maxSteps, profitLockRate, reinvestRate, target]);

  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-7 pb-12">
    <header className="rounded-[2rem] border border-border/70 bg-card/75 p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Strategy studio</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-foreground">Acumulatoare construite cu limite vizibile.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Generatorul selectează doar piețe cu valoare estimată pozitivă, evită același eveniment și limitează concentrarea pe competiție.</p></header>
    <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
      <section className="rounded-3xl border border-border/70 bg-card/70 p-6"><div className="flex items-center gap-2 text-foreground"><Calculator className="h-5 w-5 text-primary" /><h2 className="font-semibold">Țintă acumulator</h2></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[1.2, 1.4, 2].map(value => <Button key={value} variant={target === value ? "default" : "outline"} onClick={() => setTarget(value)} className="rounded-xl">Cotă {value.toFixed(2)}</Button>)}</div><div className="mt-5"><p className="text-sm font-medium text-foreground">Perioadă</p><div className="mt-2 flex flex-wrap gap-2">{([{ days: 1, label: "Doar azi" }, { days: 3, label: "Următoarele 3 zile" }, { days: 7, label: "Săptămâna curentă" }]).map(option => <Button key={option.days} size="sm" variant={horizonDays === option.days ? "default" : "outline"} onClick={() => setHorizonDays(option.days)} className="rounded-full">{option.label}</Button>)}</div></div><div className="mt-6"><Label htmlFor="target">Cotă personalizată</Label><Input id="target" type="number" min="1.05" step="0.05" value={target} onChange={event => setTarget(Number(event.target.value))} className="mt-2 rounded-xl" /></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Interval analizat: {ticketInput.targetOddsMin.toFixed(2)} – {ticketInput.targetOddsMax.toFixed(2)}. Sunt excluse selecțiile fără valoare pozitivă, din același eveniment sau cu cotă degradată cu peste 5% față de deschidere.</p></section>
      <section className="rounded-3xl border border-border/70 bg-card/70 p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-primary" /><h2 className="font-semibold text-foreground">Bilet propus</h2></div>{plan && <span className="rounded-full bg-primary/15 px-3 py-1 text-xs font-semibold text-primary">EV {plan.expectedValue > 0 ? "+" : ""}{plan.expectedValue.toFixed(1)}%</span>}</div>{suggestion.isLoading ? <p className="mt-8 text-sm text-muted-foreground">Evaluez selecțiile actuale…</p> : plan ? <><div className="mt-5 space-y-3">{plan.selections.map((selection, index) => <div key={selection.id} className="flex items-center justify-between rounded-2xl border border-border/60 bg-background/30 p-4"><div><p className="text-xs text-muted-foreground">Selecția {index + 1}</p><p className="mt-1 font-medium text-foreground">Probabilitate {selection.probability.toFixed(1)}%</p></div><p className="text-lg font-semibold text-foreground">{selection.odds.toFixed(2)}</p></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Cotă cumulată" value={plan.totalOdds.toFixed(2)} /><Metric label="Probabilitate combinată" value={`${plan.combinedProbability.toFixed(1)}%`} /></div></> : <p className="mt-8 rounded-2xl border border-dashed border-border p-5 text-sm leading-6 text-muted-foreground">Nu există încă o combinație care respectă toate condițiile pentru această țintă. Ajustează intervalul sau rulează sincronizarea datelor noi.</p>}</section>
    </div>
    <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="rounded-3xl border border-border/70 bg-card/70 p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /><h2 className="font-semibold text-foreground">Creează o piramidă</h2></div><div className="mt-5 grid grid-cols-2 gap-4"><div><Label htmlFor="stake">Miză inițială</Label><Input id="stake" type="number" value={baseStake} min="1" onChange={event => setBaseStake(Number(event.target.value))} className="mt-2 rounded-xl" /></div><div><Label htmlFor="steps">Pași maxim</Label><Input id="steps" type="number" value={maxSteps} min="1" max="31" onChange={event => setMaxSteps(Number(event.target.value))} className="mt-2 rounded-xl" /></div><div><Label htmlFor="reinvest">Reinvestire (%)</Label><Input id="reinvest" type="number" value={reinvestRate} min="5" max="100" onChange={event => setReinvestRate(Number(event.target.value))} className="mt-2 rounded-xl" /></div><div><Label htmlFor="lock">Profit protejat (%)</Label><Input id="lock" type="number" value={profitLockRate} min="0" max="90" onChange={event => setProfitLockRate(Number(event.target.value))} className="mt-2 rounded-xl" /></div></div><Button onClick={() => createPlan.mutate({ title: `Piramidă cotă ${target.toFixed(2)}`, baseStake, targetOddsMin: ticketInput.targetOddsMin, targetOddsMax: ticketInput.targetOddsMax, reinvestRate: reinvestRate / 100, profitLockRate: profitLockRate / 100, maxSteps })} disabled={createPlan.isPending} className="mt-5 w-full rounded-xl">Creează planul <ChevronRight className="ml-2 h-4 w-4" /></Button></div><div className="rounded-3xl border border-border/70 bg-card/70 p-6"><h2 className="font-semibold text-foreground">Piramidele tale</h2><div className="mt-4 space-y-3">{plans.data?.length ? plans.data.map(plan => <div key={plan.id} className="flex items-center justify-between rounded-2xl border border-border/60 bg-background/25 p-4"><div><p className="font-medium text-foreground">{plan.title}</p><p className="mt-1 text-xs text-muted-foreground">Pasul {plan.currentStep}/{plan.maxSteps} · Reinvestire {(Number(plan.reinvestRate) * 100).toFixed(0)}%</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Următoarea miză</p><p className="font-semibold text-primary">{plan.projection.stake.toFixed(2)}</p></div></div>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-foreground">Nu ai încă un plan activ. Configurează primul traseu cu o miză pe care îți permiți să o pierzi.</p>}</div></div></section>
    <section className="rounded-3xl border border-border/70 bg-card/70 p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-foreground">Simulare pe pași</h2><p className="mt-1 text-sm text-muted-foreground">Scenariu pur matematic: fiecare pas este presupus câștigător la cota țintă. Nu reprezintă un rezultat anticipat.</p></div><span className="text-xs font-semibold text-primary">Cotă simulată {target.toFixed(2)}</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-3">Nr. pariu</th><th className="pb-3">Cotă</th><th className="pb-3">Miză</th><th className="pb-3">Câștig potențial</th><th className="pb-3">Profit</th><th className="pb-3">Profit protejat</th></tr></thead><tbody>{pyramidProjection.map(row => <tr key={row.step} className="border-b border-border/50"><td className="py-3 text-foreground">{row.step}</td><td className="py-3 text-muted-foreground">{target.toFixed(2)}</td><td className="py-3 text-muted-foreground">{row.stake.toFixed(2)}</td><td className="py-3 text-foreground">{row.potentialReturn.toFixed(2)}</td><td className="py-3 text-emerald-300">+{row.profit.toFixed(2)}</td><td className="py-3 text-primary">{row.retained.toFixed(2)}</td></tr>)}</tbody></table></div></section>
  </div></DashboardLayout>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-secondary/70 p-3"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold text-foreground">{value}</p></div>; }
