import { buildSignalConsensus } from "@shared/signalConsensus";
import React from "react";

export function SignalConsensusPanel({ modelProbability, marketProbability, consensusScore, recommended }: { modelProbability: number; marketProbability: number | null; consensusScore: number | null; recommended: boolean }) {
  const consensus = buildSignalConsensus({ modelProbability, marketProbability, consensusScore, recommended });
  if (!consensus) return <p className="relative mt-3 rounded-xl border border-dashed border-border/70 px-3 py-2 text-[11px] leading-5 text-muted-foreground">Consensul va fi calculat când piața oferă o cotă reală pentru această selecție.</p>;
  const tone = consensus.alignment === "puternic" ? "text-emerald-300" : consensus.alignment === "moderat" ? "text-amber-200" : "text-rose-300";
  return <section className="relative mt-3 rounded-xl border border-border/60 bg-background/25 px-3 py-3" aria-label="Consens semnale"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-primary">Consens semnale</p><p className="mt-1 text-xs text-muted-foreground">Modelul, probabilitatea implicită din cotă și semnalul furnizorului.</p></div><p className={`font-mono text-lg font-semibold ${tone}`}>{consensus.score.toFixed(0)}<span className="text-xs text-muted-foreground">/100</span></p></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><ConsensusMetric label="Model" value={`${consensus.modelProbability.toFixed(1)}%`} /><ConsensusMetric label="Piață" value={`${consensus.marketProbability.toFixed(1)}%`} /><ConsensusMetric label="Feed" value={consensus.providerSignal} /></div><p className="mt-3 text-[11px] leading-5 text-muted-foreground">Diferență model–piață: <span className={tone}>{consensus.difference > 0 ? "+" : ""}{consensus.difference.toFixed(1)} pp</span> · aliniere {consensus.alignment}.</p></section>;
}

function ConsensusMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-border/55 bg-card/55 px-2 py-2"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 truncate text-xs font-semibold text-foreground">{value}</p></div>; }
